# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ner.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ner.proto',
  package='protogen',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\tner.proto\x12\x08protogen\"\x1b\n\nNerRequest\x12\r\n\x05input\x18\x01 \x01(\t\"\x1f\n\x0bNerResponse\x12\x10\n\x08\x65ntities\x18\x01 \x03(\t2O\n\nNerService\x12\x41\n\x12\x45xtractSubjectOrgs\x12\x14.protogen.NerRequest\x1a\x15.protogen.NerResponseb\x06proto3')
)




_NERREQUEST = _descriptor.Descriptor(
  name='NerRequest',
  full_name='protogen.NerRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='input', full_name='protogen.NerRequest.input', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=50,
)


_NERRESPONSE = _descriptor.Descriptor(
  name='NerResponse',
  full_name='protogen.NerResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='entities', full_name='protogen.NerResponse.entities', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=83,
)

DESCRIPTOR.message_types_by_name['NerRequest'] = _NERREQUEST
DESCRIPTOR.message_types_by_name['NerResponse'] = _NERRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NerRequest = _reflection.GeneratedProtocolMessageType('NerRequest', (_message.Message,), dict(
  DESCRIPTOR = _NERREQUEST,
  __module__ = 'ner_pb2'
  # @@protoc_insertion_point(class_scope:protogen.NerRequest)
  ))
_sym_db.RegisterMessage(NerRequest)

NerResponse = _reflection.GeneratedProtocolMessageType('NerResponse', (_message.Message,), dict(
  DESCRIPTOR = _NERRESPONSE,
  __module__ = 'ner_pb2'
  # @@protoc_insertion_point(class_scope:protogen.NerResponse)
  ))
_sym_db.RegisterMessage(NerResponse)



_NERSERVICE = _descriptor.ServiceDescriptor(
  name='NerService',
  full_name='protogen.NerService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=85,
  serialized_end=164,
  methods=[
  _descriptor.MethodDescriptor(
    name='ExtractSubjectOrgs',
    full_name='protogen.NerService.ExtractSubjectOrgs',
    index=0,
    containing_service=None,
    input_type=_NERREQUEST,
    output_type=_NERRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_NERSERVICE)

DESCRIPTOR.services_by_name['NerService'] = _NERSERVICE

# @@protoc_insertion_point(module_scope)
