# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import ner_pb2 as ner__pb2


class NerServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ExtractSubjectOrgs = channel.unary_unary(
        '/protogen.NerService/ExtractSubjectOrgs',
        request_serializer=ner__pb2.NerRequest.SerializeToString,
        response_deserializer=ner__pb2.NerResponse.FromString,
        )


class NerServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ExtractSubjectOrgs(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_NerServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ExtractSubjectOrgs': grpc.unary_unary_rpc_method_handler(
          servicer.ExtractSubjectOrgs,
          request_deserializer=ner__pb2.NerRequest.FromString,
          response_serializer=ner__pb2.NerResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'protogen.NerService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
