# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sentiment.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sentiment.proto',
  package='protogen',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0fsentiment.proto\x12\x08protogen\"!\n\x10SentimentRequest\x12\r\n\x05input\x18\x01 \x01(\t\"&\n\x11SentimentResponse\x12\x11\n\tsentiment\x18\x01 \x01(\x02\x32V\n\x10SentimentService\x12\x42\n\x07\x41nalyze\x12\x1a.protogen.SentimentRequest\x1a\x1b.protogen.SentimentResponseb\x06proto3')
)




_SENTIMENTREQUEST = _descriptor.Descriptor(
  name='SentimentRequest',
  full_name='protogen.SentimentRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='input', full_name='protogen.SentimentRequest.input', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=62,
)


_SENTIMENTRESPONSE = _descriptor.Descriptor(
  name='SentimentResponse',
  full_name='protogen.SentimentResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sentiment', full_name='protogen.SentimentResponse.sentiment', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=102,
)

DESCRIPTOR.message_types_by_name['SentimentRequest'] = _SENTIMENTREQUEST
DESCRIPTOR.message_types_by_name['SentimentResponse'] = _SENTIMENTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SentimentRequest = _reflection.GeneratedProtocolMessageType('SentimentRequest', (_message.Message,), dict(
  DESCRIPTOR = _SENTIMENTREQUEST,
  __module__ = 'sentiment_pb2'
  # @@protoc_insertion_point(class_scope:protogen.SentimentRequest)
  ))
_sym_db.RegisterMessage(SentimentRequest)

SentimentResponse = _reflection.GeneratedProtocolMessageType('SentimentResponse', (_message.Message,), dict(
  DESCRIPTOR = _SENTIMENTRESPONSE,
  __module__ = 'sentiment_pb2'
  # @@protoc_insertion_point(class_scope:protogen.SentimentResponse)
  ))
_sym_db.RegisterMessage(SentimentResponse)



_SENTIMENTSERVICE = _descriptor.ServiceDescriptor(
  name='SentimentService',
  full_name='protogen.SentimentService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=104,
  serialized_end=190,
  methods=[
  _descriptor.MethodDescriptor(
    name='Analyze',
    full_name='protogen.SentimentService.Analyze',
    index=0,
    containing_service=None,
    input_type=_SENTIMENTREQUEST,
    output_type=_SENTIMENTRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SENTIMENTSERVICE)

DESCRIPTOR.services_by_name['SentimentService'] = _SENTIMENTSERVICE

# @@protoc_insertion_point(module_scope)
